#!/usr/bin/perl

use strict;
use URI::Escape;
use IO::Socket::INET;

print "Content-type: application/json\n\n";

my $netrap = new IO::Socket::INET(Proto    => 'tcp',
                               PeerAddr => '192.168.1.13',
                               PeerPort => '2560');

if (! defined $netrap) {
	print '{ "status": "failure: ' . $@ . '" }';
	exit(0);
}

my @replies;

while (<>) {
	print $netrap $_;
	print stderr $_;
	my $reply = <$netrap>;
	chomp $reply;
	push @replies, $reply;
}
$netrap->close();

print "{ \"status\": \"success\", \"replies\": [ ";
my $first = 1;
for (@replies) {
	print ", " unless $first; $first = 0;
	my $reply = $_;
	$reply =~ s/"/\\"/g;
	print "\"$reply\"";
}
print " ] }";
